apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-auth
data:
  model.conf: |
    # This is the default Casbin model for the workflow controller
    [request_definition]
    r = workflowNamespace, cluster, namespace
    
    [policy_definition]
    p = workflowNamespace, cluster, namespace
    
    [policy_effect]
    e = some(where (p.eft == allow))
    
    [matchers]
    # workflows may create resources in their own cluster and namespace OR it may create a resource only if it has a policy
    m = r.workflowNamespace == r.namespace && r.cluster == "" || r.workflowNamespace == p.workflowNamespace && r.cluster == p.cluster && r.namespace == p.namespace
  policy.csv: ""