apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/crds/minimal/argoproj.io_workflowtaskresults.yaml
  - argo.cluster-0-serviceaccount.yaml
  - argo.cluster-0-role.yaml
  - argo.cluster-0-rolebinding.yaml
  - argo-server.cluster-0-serviceaccount.yaml
  - argo-server.cluster-0-role.yaml
  - argo-server.cluster-0-rolebinding.yaml