apiVersion: v1
data:
  model.conf: |-
    [request_definition]
    r = sub, obj, act

    [policy_definition]
    p = sub, obj, act

    [role_definition]
    g = _, _

    [policy_effect]
    e = some(where (p.eft == allow))

    [matchers]
    m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act

    [matchers]
    m = g(r.sub, p.sub) && keyMatch(r.sub, p.sub) && keyMatch(r.obj, p.obj) && (contains(p.acts, r.act) || p.acts == '*')
  policy.csv: |
    # The argo-server has read-write access in cluster-0.
    p, serviceaccount:cluster-0:argo:argo-server, cluster-0:*, *
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: argo-server-authz
