apiVersion: v1
data:
  model.conf: |-
    [request_definition]
    r = sub, obj, act

    [policy_definition]
    p = sub, obj, acts

    [policy_effect]
    e = some(where (p.eft == allow))

    [matchers]
    m = keyMatch(r.sub, p.sub) && keyMatch(r.obj, p.obj) && (contains(p.acts, r.act) || p.acts == '*')
  policy.csv: ""
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: argo-server-authz
